# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import audio_capture_service_pb2 as audio__capture__service__pb2


class AudioCapturerStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartCapture = channel.unary_stream(
                '/AudioService.AudioCapturer/StartCapture',
                request_serializer=audio__capture__service__pb2.ProcessToCapture.SerializeToString,
                response_deserializer=audio__capture__service__pb2.AudioPacket.FromString,
                )
        self.StopCapture = channel.unary_unary(
                '/AudioService.AudioCapturer/StopCapture',
                request_serializer=audio__capture__service__pb2.Empty.SerializeToString,
                response_deserializer=audio__capture__service__pb2.Empty.FromString,
                )
        self.Status = channel.unary_unary(
                '/AudioService.AudioCapturer/Status',
                request_serializer=audio__capture__service__pb2.Empty.SerializeToString,
                response_deserializer=audio__capture__service__pb2.Availability.FromString,
                )
        self.Shutdown = channel.unary_unary(
                '/AudioService.AudioCapturer/Shutdown',
                request_serializer=audio__capture__service__pb2.Empty.SerializeToString,
                response_deserializer=audio__capture__service__pb2.Empty.FromString,
                )


class AudioCapturerServicer(object):
    """The greeting service definition.
    """

    def StartCapture(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopCapture(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AudioCapturerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartCapture': grpc.unary_stream_rpc_method_handler(
                    servicer.StartCapture,
                    request_deserializer=audio__capture__service__pb2.ProcessToCapture.FromString,
                    response_serializer=audio__capture__service__pb2.AudioPacket.SerializeToString,
            ),
            'StopCapture': grpc.unary_unary_rpc_method_handler(
                    servicer.StopCapture,
                    request_deserializer=audio__capture__service__pb2.Empty.FromString,
                    response_serializer=audio__capture__service__pb2.Empty.SerializeToString,
            ),
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=audio__capture__service__pb2.Empty.FromString,
                    response_serializer=audio__capture__service__pb2.Availability.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=audio__capture__service__pb2.Empty.FromString,
                    response_serializer=audio__capture__service__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AudioService.AudioCapturer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AudioCapturer(object):
    """The greeting service definition.
    """

    @staticmethod
    def StartCapture(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/AudioService.AudioCapturer/StartCapture',
            audio__capture__service__pb2.ProcessToCapture.SerializeToString,
            audio__capture__service__pb2.AudioPacket.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopCapture(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AudioService.AudioCapturer/StopCapture',
            audio__capture__service__pb2.Empty.SerializeToString,
            audio__capture__service__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AudioService.AudioCapturer/Status',
            audio__capture__service__pb2.Empty.SerializeToString,
            audio__capture__service__pb2.Availability.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AudioService.AudioCapturer/Shutdown',
            audio__capture__service__pb2.Empty.SerializeToString,
            audio__capture__service__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
