# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: audio_capture_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x61udio_capture_service.proto\x12\x0c\x41udioService\"\x1f\n\x10ProcessToCapture\x12\x0b\n\x03pid\x18\x01 \x01(\r\"L\n\x0b\x41udioPacket\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x12\n\nnum_frames\x18\x02 \x01(\r\x12\x16\n\x0e\x63\x61ptured_audio\x18\x03 \x01(\x0c\"@\n\x0c\x41vailability\x12\x30\n\x06status\x18\x01 \x01(\x0e\x32 .AudioService.AvailabilityStatus\"\x07\n\x05\x45mpty*4\n\x12\x41vailabilityStatus\x12\r\n\tAVAILABLE\x10\x00\x12\x0f\n\x0bUNAVAILABLE\x10\x01\x32\x86\x02\n\rAudioCapturer\x12K\n\x0cStartCapture\x12\x1e.AudioService.ProcessToCapture\x1a\x19.AudioService.AudioPacket0\x01\x12\x37\n\x0bStopCapture\x12\x13.AudioService.Empty\x1a\x13.AudioService.Empty\x12\x39\n\x06Status\x12\x13.AudioService.Empty\x1a\x1a.AudioService.Availability\x12\x34\n\x08Shutdown\x12\x13.AudioService.Empty\x1a\x13.AudioService.Emptyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audio_capture_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AVAILABILITYSTATUS._serialized_start=231
  _AVAILABILITYSTATUS._serialized_end=283
  _PROCESSTOCAPTURE._serialized_start=45
  _PROCESSTOCAPTURE._serialized_end=76
  _AUDIOPACKET._serialized_start=78
  _AUDIOPACKET._serialized_end=154
  _AVAILABILITY._serialized_start=156
  _AVAILABILITY._serialized_end=220
  _EMPTY._serialized_start=222
  _EMPTY._serialized_end=229
  _AUDIOCAPTURER._serialized_start=286
  _AUDIOCAPTURER._serialized_end=548
# @@protoc_insertion_point(module_scope)
