# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: led_controller_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cled_controller_service.proto\x12\x11\x43ontrollerService\"\x1b\n\x05\x43olor\x12\x12\n\nrgba_color\x18\x01 \x03(\r\"E\n\x0c\x41vailability\x12\x35\n\x06status\x18\x01 \x01(\x0e\x32%.ControllerService.AvailabilityStatus\"\x07\n\x05\x45mpty*[\n\x12\x41vailabilityStatus\x12\x11\n\rALL_AVAILABLE\x10\x00\x12\x1d\n\x19\x41UDIO_CAPTURE_UNAVAILABLE\x10\x01\x12\x13\n\x0f\x41LL_UNAVAILABLE\x10\x02\x32\xd4\x01\n\rLEDController\x12>\n\x08SetColor\x12\x18.ControllerService.Color\x1a\x18.ControllerService.Empty\x12>\n\x08GetColor\x12\x18.ControllerService.Empty\x1a\x18.ControllerService.Color\x12\x43\n\x06Status\x12\x18.ControllerService.Empty\x1a\x1f.ControllerService.Availabilityb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'led_controller_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AVAILABILITYSTATUS._serialized_start=160
  _AVAILABILITYSTATUS._serialized_end=251
  _COLOR._serialized_start=51
  _COLOR._serialized_end=78
  _AVAILABILITY._serialized_start=80
  _AVAILABILITY._serialized_end=149
  _EMPTY._serialized_start=151
  _EMPTY._serialized_end=158
  _LEDCONTROLLER._serialized_start=254
  _LEDCONTROLLER._serialized_end=466
# @@protoc_insertion_point(module_scope)
