# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import led_controller_service_pb2 as led__controller__service__pb2


class LEDControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetColor = channel.unary_unary(
                '/ControllerService.LEDController/SetColor',
                request_serializer=led__controller__service__pb2.Color.SerializeToString,
                response_deserializer=led__controller__service__pb2.Empty.FromString,
                )
        self.GetColor = channel.unary_unary(
                '/ControllerService.LEDController/GetColor',
                request_serializer=led__controller__service__pb2.Empty.SerializeToString,
                response_deserializer=led__controller__service__pb2.Color.FromString,
                )
        self.Status = channel.unary_unary(
                '/ControllerService.LEDController/Status',
                request_serializer=led__controller__service__pb2.Empty.SerializeToString,
                response_deserializer=led__controller__service__pb2.Availability.FromString,
                )


class LEDControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetColor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetColor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LEDControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetColor': grpc.unary_unary_rpc_method_handler(
                    servicer.SetColor,
                    request_deserializer=led__controller__service__pb2.Color.FromString,
                    response_serializer=led__controller__service__pb2.Empty.SerializeToString,
            ),
            'GetColor': grpc.unary_unary_rpc_method_handler(
                    servicer.GetColor,
                    request_deserializer=led__controller__service__pb2.Empty.FromString,
                    response_serializer=led__controller__service__pb2.Color.SerializeToString,
            ),
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=led__controller__service__pb2.Empty.FromString,
                    response_serializer=led__controller__service__pb2.Availability.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ControllerService.LEDController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LEDController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetColor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ControllerService.LEDController/SetColor',
            led__controller__service__pb2.Color.SerializeToString,
            led__controller__service__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetColor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ControllerService.LEDController/GetColor',
            led__controller__service__pb2.Empty.SerializeToString,
            led__controller__service__pb2.Color.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ControllerService.LEDController/Status',
            led__controller__service__pb2.Empty.SerializeToString,
            led__controller__service__pb2.Availability.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
