# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\"$\n\x0fSetColorRequest\x12\x11\n\trgb_color\x18\x01 \x03(\r\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t26\n\x07Greeter\x12+\n\x08SetColor\x12\x10.SetColorRequest\x1a\x0b.HelloReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SETCOLORREQUEST._serialized_start=14
  _SETCOLORREQUEST._serialized_end=50
  _HELLOREPLY._serialized_start=52
  _HELLOREPLY._serialized_end=81
  _GREETER._serialized_start=83
  _GREETER._serialized_end=137
# @@protoc_insertion_point(module_scope)
